# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build
FROM node:16-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the source code
COPY . .

# Build the project
RUN npm run build

# Stage 2: Run
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy only the necessary files
COPY --from=builder /app/dist /app/dist
COPY package.json ./

# Set environment variables (you should set this in your environment or secrets)
ENV WEBFLOW_API_TOKEN=your-api-token

# Install production dependencies
RUN npm install --production

# Start the server
ENTRYPOINT ["node", "dist/index.js"]
